### ISSUE TITLE
Způsob měření vlhkosti a teploty

### ISSUE THREAD

**Issue by kaklik** [UniversalScientificTechnologies/THUNDERMILL01#1]
Pro správnou funkci mlýnku bude zřejmě potřeba měřit teplotu a vlhkost okolního vzduchu. 
Nejlepší dostupné řešení zřejmě je data logovat pomocí autopilota a snímače [TFHT01](https://github.com/ThunderFly-aerospace/TFHT01)

Alternativně může být stejný snímač připojen do [obslužného MCU](https://github.com/UniversalScientificTechnologies/THUNDERMILL01/issues/4).

**Comment by kaklik** [comment]
Pro případ vírníku TF-G2 bych navrhoval, tohle měření shovat do krytu dílu [TFSLOT](https://github.com/ThunderFly-aerospace/TFSLOT01), který bude součástí rotorového pylonu.

**Comment by roman-dvorak** [comment]
Myslím, že pokud bude procesor na PCB mlýnku, tak je docela logické to umístit přimo na něj. Protože tak obslouží více věcí zároveň.

**Comment by ChroustJan** [comment]
Kam by měl být ten senzor připojený? Do autopilota nebo toho procesoru mlýnku?

**Comment by roman-dvorak** [comment]
Do procesoru mlýnku

**Comment by kaklik** [comment]
Ve schéma je nyni zakreslen typ SHT31. Na rozdíl od SHT35, který má být používán v TFHT01. 

![image](https://user-images.githubusercontent.com/1194177/130417931-108dc35d-ac21-4fb3-b315-528458c1c5bc.png)

Vzhledem k tomu, že tyto dva typy se liší pouze přesností měření. Jinak jsou funkčně i elektricky a mechanicky ekvivalentní, tak toto issue považuji za vyřešené.
