### ISSUE TITLE
Konstrukce snímacích elektrod

### ISSUE THREAD

**Issue by kaklik** [UniversalScientificTechnologies/THUNDERMILL01#2]
Snímací elektrody budou pravděpodobně realizovány z PCB a namontovány na rotorovou hlavu [TF-G2](https://github.com/ThunderFly-aerospace/TF-G2/tree/THUNDERMILL01). 

![153322634_434024251155473_6229406597574792622_n](https://user-images.githubusercontent.com/1194177/113276760-72b92d00-92e0-11eb-9f04-ed46aea0a825.jpg)

![153627614_1083384738832953_691668326880582031_n](https://user-images.githubusercontent.com/1194177/113276768-7482f080-92e0-11eb-834b-95d5a5d846e1.jpg)

Rotorová hlava měřícího vírníku aktuálně vypadá přibližně takto: 

![assembly_thundermill](https://user-images.githubusercontent.com/1194177/129482049-c9f090f7-c6a5-48d2-8d17-efa547bedfef.png)

K vyřešení je potřeba: 

- [x] Vytvořit návrh PCB elektrod
- [x] Upravit [rotorovou hlavu vírníku TF-G2](https://github.com/ThunderFly-aerospace/TF-G2/blob/THUNDERMILL01/CAD/stl/position_rotorhead.stl) - Zobrazené STL je výstupem [tohoto zdrojového kódu](https://github.com/ThunderFly-aerospace/TF-G2/blob/THUNDERMILL01/CAD/src/assembly/position/position_rotorhead.scad).

Při úpravách by bylo vhodné zohlednit fakt, že je výhodné, aby se [rotorová hlava při nárazu rozlomila](https://github.com/ThunderFly-aerospace/TF-G2/issues/69)  a tím byly před poškozením ochráněny ostatní části vírníku. 

Roztáčení provázkem bude nahrazeno roztáčením stuhou.

**Comment by kaklik** [comment]
@Alsa-Tucnak  Tady je fotografie skutečné realizace aktuálního návrhu rotorové hlavy: 

![image](https://user-images.githubusercontent.com/1194177/111808484-57a7ef80-88d4-11eb-95ad-c5ddb96ca756.png)

**Comment by kaklik** [comment]
@Alsa-Tucnak  Upravila návrh rotorového bubínku. 

![image](https://user-images.githubusercontent.com/1194177/117039771-725de880-ad09-11eb-835e-3eb93703b2d4.png)

Je to výrazný pokrok, ale je potřeba vyřešit některé technologické problémy. :)  Zkusím popsat jak bych navrhoval postupovat. 

- [x]  Model se tiskne tak, že následující obrázek je při tisku pohledem nahoru od podložky, jak je vidět tak ten kruhový lem vytvoří převis, který nepůjde vytisknout. Navrhoval bych průměr lemu srovnat s kuželovou částí  současného modelu. (Jde buď trošku změnit úhel kuželové části a nebo změnit průměr lemu, případně části která tvoří bubínek pro namotávání stuhy)
![image](https://user-images.githubusercontent.com/1194177/117043352-6542f880-ad0d-11eb-9474-1fef349ffdb6.png)

- [x] Kapsa pro matici v tomto uspořádání nepůjde vytisknout, protože se zbortí její stěny (hlavně strop)
![image](https://user-images.githubusercontent.com/1194177/117046145-9cff6f80-ad10-11eb-8057-fbb423995ba5.png) 
Navrhoval bych situaci vyřešit tak, že z tého vnitřní strany bude kapsa plně uzavřena a matice se bude vkládat naopak z venku. Myšleno otvorem v této stěně: 
![image](https://user-images.githubusercontent.com/1194177/117046299-d20bc200-ad10-11eb-8439-16bf722d1dfd.png)
Důsledkem kromě snažšího tisku a jednodušší montáže bude i to, že do ložisek rotoru v tomto místě nebude možné, aby tudy tekla voda (Šrouby vůbec nepovedou do vnitřního objemu). Trochu jsem se tuto možnost snažil naznačit už v popisu [souvisejícího issue](https://github.com/ThunderFly-aerospace/TF-G2/issues/95#issuecomment-826138831). 

- [x] velmi složitá část modelu sloužící jako kapsa pro matky k přišroubování PCB s elektrodami má také problém s tiskem
![image](https://user-images.githubusercontent.com/1194177/117046931-8f96b500-ad11-11eb-954a-e832f789400e.png)
Navrhoval bych zde model zjednodušit pouze na obyčejné otvory v tištěném modelu o průměru třeba 1.5mm do kterých se zašroubují samořezné šrouby s půlkulatou hlavou. Otvory jsou naznačeny červenými puntíky v následujícím obrázku:
![Screenshot from 2021-05-04 19-49-20](https://user-images.githubusercontent.com/1194177/117050510-b656ea80-ad15-11eb-8352-64e5ee7bdee4.png)

**Comment by kaklik** [comment]
Ještě mě k tomu napadlo, že ten navrhovaný tvar PCB by chtělo nejdřív nakreslit v openscadu, vytisknout a zkusit s tím letět.  Měření otáček se dá myslím vyřešit zakomponováním stávajícího [TFPROBE](https://github.com/ThunderFly-aerospace/TFPROBE01) do tištěné plochy.

**Comment by kaklik** [comment]
@Alsa-Tucnak  udělala další iteraci úprav dílů rotorové hlavy. 

![186498421_4267764183243776_6886709830986274375_n](https://user-images.githubusercontent.com/1194177/118396148-6dc0fa80-b64e-11eb-90a0-6b979916a3cf.png)

![186995108_475693990429516_7914114588060035971_n](https://user-images.githubusercontent.com/1194177/118396150-70235480-b64e-11eb-88de-b61d5e765e0b.png)

Až na detaily vedoucí k vyřešení potíží s [bezpečným ulamováním rotorové hlavy](https://github.com/ThunderFly-aerospace/TF-G2/issues/69).  Je návrh z hlediska mechanické itegrace mlýnku kompletní. 

Dalším krokem je tak návrh 3D tištěného demostrátoru PCB (měřících elektrod), který bude obsahovat i TFPROBE, jak je navrhováno v[ komentáři výše](https://github.com/UniversalScientificTechnologies/THUNDERMILL01/issues/2#issuecomment-841535213).  S takovým mechanickým prototypem by bylo vhodné zkusit provést testovací let, aby se ověřilo, že vliv elektrod na letové vlastnosti není významný.

**Comment by kaklik** [comment]
### Horní díl (klobouček rotoru)

 Při vytišnění klouboučku pro rotorové listy se ukázaly tyhle problematické části. 

Matice nepasují do kapsy pro matici, která je moc nízká.  

![image](https://user-images.githubusercontent.com/1194177/120395279-089b2380-c335-11eb-9882-21c6f63f2856.png)

Celkově je potřeba u horního dílu vyřešit

- [x] Výška kapsy pro matice
- [x] Tolerance otvorů pro šrouby sloužící k upevnění rotujícího kotoučku mlýnku
- [x] Zuby na kulatém válci pro namotávání tkaničky (díky nepoužití proměnné draft, pro přepínání rozlišení)

### Spodní díl (Základna s ložisky)

- [x] Způsob montáže vyměňovacího sloupku (Asi šrouby vertikálně pro snadnou výměnu)
- [x] Šroub držící osu roll chytit ve spodním dílu tak, aby nevypadl při výměně lámacího sloupku

**Comment by kaklik** [comment]
Aktualizovaný návrh provedení plošného spoje. 

![image](https://user-images.githubusercontent.com/1194177/129482230-6332f083-9bd2-4723-b10a-c57b671b3aa0.png)

[Scan v plném rozlišení. ](https://github.com/UniversalScientificTechnologies/THUNDERMILL01/blob/THUNDERMILL01A/doc/PCB_design.PDF)

**Comment by roman-dvorak** [comment]
![obrazek](https://user-images.githubusercontent.com/5196729/130069961-98730d37-ade5-4af6-b1d5-ff33bc5fbf81.png)

![obrazek](https://user-images.githubusercontent.com/5196729/130070002-a416c558-0c68-4460-98b5-ab32ccf2cec9.png)

![obrazek](https://user-images.githubusercontent.com/5196729/130070203-ff1da30a-387e-4b0c-a359-578786b0d9f5.png)

![obrazek](https://user-images.githubusercontent.com/5196729/130070622-5dea9cf1-cd58-4b4f-8412-83977ecd0d76.png)

![obrazek](https://user-images.githubusercontent.com/5196729/130070771-37a8b0a6-0f7e-43ee-a6ef-133011c50299.png)

![image](https://user-images.githubusercontent.com/5196729/130151637-72819d76-2e29-4abe-adb3-018386e0d7a5.png)




Pro programování MCU: 

Kamkoliv do prostoru umístit 6 (kulatých) plošek pro poggo piny. Rozteč mezi piny nechme 2.54 mm. Je mi jedno, jestli budou uspořádané jako 2x3 nebo 1x6. Nelzáleží mi ani na pinoutu.
