### ISSUE TITLE
Návrh snímací elektroniky

### ISSUE THREAD

**Issue by kaklik** [UniversalScientificTechnologies/THUNDERMILL01#3]
Snímací elektrody z #2  budou potřebovat analogovou elektroniku pro zpracování signálu. 
Tato elektronika by měla mít rozhraní vhodné k připojení k [obslužnému MCU](https://github.com/UniversalScientificTechnologies/THUNDERMILL01/issues/4). 

Analogová elektronika by zřejmě měla být součástí měřících elektrod #2. Z té se pak vyvedou pouze signály potřebné pro připojení k obslužnému MCU #4 .

**Comment by kaklik** [comment]
Zapojeni pro prototyp mlýnku. FYI @ChroustJan 

![217787685_923520351565344_7205702136655300835_n](https://user-images.githubusercontent.com/1194177/126672207-d5860ca6-4d7d-462d-86c5-49be2152cebd.jpg)

**Comment by kaklik** [comment]
Zde jsou [doplňující požadavky na schéma](https://github.com/UniversalScientificTechnologies/THUNDERMILL01/blob/THUNDERMILL01A/doc/sensors.PDF) reflexivních snímačů.


![image](https://user-images.githubusercontent.com/1194177/129482315-a85d5d0c-c3fa-4aae-94a1-f15d6925d47a.png)

**Comment by roman-dvorak** [comment]
Před návrhem a výrobou je potřeba otestovat nové zapojení indikační LED u čítače o otáček s moduly TFRPM nebo s MLAB variantou modulu. Takovéto užití pinu není v datasheetu přímo uvedené.

**Comment by kakl** [comment]
> Před návrhem a výrobou je potřeba otestovat nové zapojení indikační LED u čítače o otáček s moduly TFRPM nebo s MLAB variantou modulu. Takovéto užití pinu není v datasheetu přímo uvedené.

to se musi udelat po pripojeni k autopilotu po pnastaveni citace
pro me je to tezke nasimulovat

**Comment by kaklik** [comment]
Signál na OSCO při otáčení současným kotoučkem THUNDERMILL. Snímač připojen k autopilotu ve vírníku, jeho inicializaci jsem neověřoval, ale předpokládám, že proběhla.  Očekával bych navíc, že invertor mezi OSCI a OSCO je zadrátován hardwarově.

![Newfile1](https://user-images.githubusercontent.com/1194177/129573882-6feff759-d8e4-4de4-b1fd-04df96bcbfc8.png)

![Newfile2](https://user-images.githubusercontent.com/1194177/129573885-44c08aa6-ec04-4a73-b80c-58e4a7e8c3c5.png)

Je tak asi potřeba jen zajistit, aby LED svítila viditelně intenzivně ze spodu kotoučku i za dne při nepřekročení těch 10mA, který ten výstup má ve specifikaci.  

Nepřekročení zatížení OSCO lze dosáhnout například tím, že signál bude připojen k MCU #4  a ten teprve bude blikat nějakou LED připojenou ke svému pinu.

**Comment by roman-dvorak** [comment]
Požadavky na přípojní elektroniky:

- [x] JST-GH konektor pro I2C z čítače otáček do autopilota (Donecode I2C port)
- [x] JST-GH UART konektor pro přípojení MCU do autopilota (Dronecode telemetry port)
- [x] JST-GH konektor jako vývod analogového signálu z mlýnku
- [x] Propojení elektrod
  - [x] Ploška pro připájení vodiče z rotačního disku
  - [x] Ploška pro připájení vodiče ze spodní elektrody
- [x] JST-GH konektor pro připojení [TFPAYLOAD konektoru z GPS (TF zapojení)](https://github.com/ThunderFly-aerospace/TFGPS01#payload-conector)
  - [x] PPS signál do MCU
  - [x] RX/TX na druhý UART MCU
  - Co s I2C z GPS? Nechat ho odpojený? nebo je potřeba ho zapojit do MCU
- [x] LED pro signalizaci funkce RPM senzoru (z PCF8583)
- [x] LED pro signalizaci funkce MCU

**Comment by kaklik** [comment]
Transil bych navrhoval použít tenhle: https://www.tme.eu/cz/details/uclamp3312t.tct/transil-diody-obousmerne-smd/semtech/
Není asi úplně praktický že je dvojitej, ale při jeho velikosti by to asi nemělo vadit.

**Comment by ChroustJan** [comment]
@kaklik nemohl by jsi prosím najít jiný třeba u jiného dodavatele? S nějakým normálním pouzdrem? Tento jsem našel taky, ale zavrhl.

**Comment by ChroustJan** [comment]
Využit tento transil: UCLAMP3301H.TCT

**Comment by kaklik** [comment]
Ve schématu je špatně, že je tam značka bipolárního transilu a ve skutečnosti je použit unipolární.

**Comment by kaklik** [comment]
>
>  Co s I2C z GPS? Nechat ho odpojený? nebo je potřeba ho zapojit do MCU
> 

V případě použití čtyřvrstvého plošného spoje podle mě nění důvod tyto piny na PAYLOAD konektoru nezapojovat.  I2C na tomto konektoru bych ale navrhoval zapojit přes 100ohm rezistory, neboť potřebujeme, aby primárně fungovalo čidlo a paměť přímo na mlýnku. Použití I2C rozhraní GPS je option. 

Zbylé piny z payload konektoru, jsou EXTINT, GEO_STAT, SDA, SCL.  Všechny se kromě I2C mohou připojit na libovolné piny MCU. 

![image](https://user-images.githubusercontent.com/1194177/130413402-4873965b-cee9-42dd-89e3-24822e95fb64.png)

**Comment by ChroustJan** [comment]
@kaklik tak tedy takto? https://github.com/UniversalScientificTechnologies/USTTHUNDERMILLPCB01/blob/USTTHUNDERMILLPCB01A/hw/sch_pcb/USTTHUNDERMILLPCB01A/USTTHUNDERMILLPCB01A.pdf

**Comment by kaklik** [comment]
Moje poznámka je v aktuální verzi vyřešena.
