### ISSUE TITLE
Obslužný mikrokontroler

### ISSUE THREAD

**Issue by kaklik** [UniversalScientificTechnologies/THUNDERMILL01#4]
Celé zařízení by mělo být senzorem systému [TF-ATMON](https://www.thunderfly.cz/tf-atmon.html), který předpokládá připojení snímačů přes MCU desku [TFUNIPAYLOAD01](https://github.com/ThunderFly-aerospace/TFUNIPAYLOAD01). Snímací elektronika #3 by se tak měla připojovat k této MCU desce.

**Comment by kaklik** [comment]
Zatím to lze testovat na [DATALOGGER01](https://github.com/mlab-modules/DATALOGGER01).

**Comment by kaklik** [comment]
Alternativní možnosti realizace jsou: 

## Přidání MCU přímo na snímací statický kotouček

Ze spodní strany je na snímacím kotoučku pravděpodobně dost místa na to, aby zde mohl být umístěn i MCU z TFUNIPAYLOAD. 

## Vzorkování signálu MCU z autopilota

Takový postup by vyžadoval zakódovat nulovou pozici do analogového signálu.  Výhodou by bylo, že 
  1. nemusíme mít hned nakreslený TFUNIPAYLOAD.  
  2. Ušetříme hmotnost. 
  3. Nebude potíž se synchronizací dat k ostatním datům z autopilota, protože to může celé logovat rovnou autopilot. Ten určitě umí logovat ADC 100Hz viz https://px4.github.io/Firmware-Doxygen/d6/dec/class_a_d_c.html#a234ca7690a8648d6a1db818b0cf4d816  Možná by to ale mohlo jít nastavit i na rychlejší hodnotu, pokud je to potřeba.

Autopilot má [dva ADC kanály na jednom konektoru na kterém je k dispozici i 5V napájení.](https://raw.githubusercontent.com/cuav/hardware/master/V5_Autopilot/V5_NANO/RC03/V5_NANO_RC03.pdf)

Překážkou k realizace této metody je, že nevíme, zda ADC autopilota umí vzorkovat 1MSPS, který se aktuálně používá v testovacím prototypu mlýnku. 

Nicméně by asi bylo vhodné, aby snímací elektronika #3 Umožňovala obě tyto možnosti připojení. Což se ale bude hodit i kvůli diagnostickým účelům.

**Comment by kaklik** [comment]
@kakl  je zřejmě potřeba pro @ChroustJan  připravit schéma zapojení včetně MCU.  Což zřejmě znamená vytisknout a proškrtat zapojení [DATALOGGER01](https://github.com/mlab-modules/DATALOGGER01).

**Comment by kaklik** [comment]
Zde je [scan proškrtaného schéma](https://github.com/UniversalScientificTechnologies/THUNDERMILL01/blob/THUNDERMILL01A/doc/MCU_schematics.PDF) DATALOGGER01. 

![image](https://user-images.githubusercontent.com/1194177/129482184-722aaf39-89fc-44cb-a464-f11b1722f768.png)

1. Kromě výše uvedených úprav by se hodilo na nějaké volné piny MCU přidat v programu univerzálně použitelné LED. 
2. Dále zde zřejmě chybí konektor po TFGPS.

**Comment by kaklik** [comment]
K MCU je vhodné použít například [tento krystal](https://www.tme.eu/cz/details/16.00m-cfpx-218/krystalove-rezonatory-smd/iqd-frequency-products/lfxtal069392cutt/). Zároveň je však nutné opravit chybu https://github.com/mlab-modules/DATALOGGER01/issues/1 

Společně s ním by bylo vhodné pořídit i [jeho 20MHz verzi](https://www.tme.eu/cz/details/20.00m-cfpx218/krystalove-rezonatory-smd/iqd-frequency-products/lfxtal052896cutt/) pro případ, že by bylo nutné zvednout pracovní frekvenci MCU.

**Comment by ChroustJan** [comment]
Je použitelný pro kapacity v tomto pásmu?
![image](https://user-images.githubusercontent.com/9783606/130021308-7dcdb8bd-511e-424a-bcfe-9cc23d88abbb.png)

**Comment by kaklik** [comment]
> Je použitelný pro kapacity v tomto pásmu?
> ![image](https://user-images.githubusercontent.com/9783606/130021308-7dcdb8bd-511e-424a-bcfe-9cc23d88abbb.png)

Neuvědomuji si žádný důvod proč by nebyl.

**Comment by ChroustJan** [comment]
Bude použit tento krystal: https://www.tme.eu/cz/details/16.00m-cfpx180/krystalove-rezonatory-smd/iqd-frequency-products/lfxtal035264reel/

**Comment by kaklik** [comment]
> Bude použit tento krystal: https://www.tme.eu/cz/details/16.00m-cfpx180/krystalove-rezonatory-smd/iqd-frequency-products/lfxtal035264reel/

Jeho alternativní typ pro 20MHz je [tento](https://www.tme.eu/cz/details/20.00m-cfpx180/krystalove-rezonatory-smd/iqd-frequency-products/lfxtal035265reel/).

**Comment by kaklik** [comment]
Úkoly z tohoto issue jsou implementovány a oba krystaly přesunuty do nákupního seznamu.
